[package]
name = "shade_otc_verifier"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anchor-lang = "0.27.0"
anchor-spl = "0.27.0"
sha2 = "0.10.6"

[features]
default = []
onchain_verifier = []
